/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RealizarTestes.java
 *
 * Created on 17/01/2012, 00:53:02
 */
package weka.ui;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import weka.Functions;

/**
 *
 * @author pedroholanda
 */
public class RealizarTestes extends javax.swing.JFrame {

    /** Creates new form Testes */
    public RealizarTestes() {
        initComponents();
    }

    public void setDiretorio(String diretorioArquivo) {
        diretorio = diretorioArquivo;
        jDiretorio.setText(diretorio);

    }
    private static int buttonSelected = 0;
    private static String diretorio;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DadosAcesso = new javax.swing.JPanel();
        jPovoar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jDiretorio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFolds = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DadosAcesso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Realizar Testes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPovoar.setText("Cross-Validation");
        jPovoar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPovoarActionPerformed(evt);
            }
        });

        jLabel6.setText("Arquivo ARFF:");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("MultiLayer Perceptron");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("RadialBasis Function");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("LearningRate:");

        jLabel2.setText("Training Time:");

        jLabel3.setText("Layers:");

        jLabel4.setText("Clusters:");

        jLabel7.setText("Folds (CrossValidation):");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Regressão Linear");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout DadosAcessoLayout = new org.jdesktop.layout.GroupLayout(DadosAcesso);
        DadosAcesso.setLayout(DadosAcessoLayout);
        DadosAcessoLayout.setHorizontalGroup(
            DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(DadosAcessoLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel7)
                .add(26, 26, 26)
                .add(jFolds, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(DadosAcessoLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(DadosAcessoLayout.createSequentialGroup()
                        .add(DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jRadioButton1))
                        .add(29, 29, 29)
                        .add(DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jPovoar)
                                .add(DadosAcessoLayout.createSequentialGroup()
                                    .add(jRadioButton2)
                                    .add(18, 18, 18)
                                    .add(jRadioButton3))))
                        .add(173, 173, 173))
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(161, 161, 161))
            .add(DadosAcessoLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel6)
                .add(18, 18, 18)
                .add(jDiretorio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 176, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton1)
                .addContainerGap())
        );
        DadosAcessoLayout.setVerticalGroup(
            DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(DadosAcessoLayout.createSequentialGroup()
                .add(DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(DadosAcessoLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel6))
                    .add(DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jDiretorio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButton1)))
                .add(9, 9, 9)
                .add(DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(DadosAcessoLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel7))
                    .add(jFolds, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton1)
                    .add(jRadioButton2)
                    .add(jRadioButton3))
                .add(DadosAcessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(DadosAcessoLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel1)
                        .add(22, 22, 22)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel3)
                        .add(10, 10, 10)
                        .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(DadosAcessoLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 99, Short.MAX_VALUE)
                        .add(jPovoar)
                        .add(42, 42, 42))))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(DadosAcesso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 590, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(DadosAcesso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jPovoarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPovoarActionPerformed
    String folds = jFolds.getText();
    String diretorio = jDiretorio.getText();
    String allData = null;
    Functions weka = new Functions();
    if (buttonSelected == 1) {
        String learningRate = jTextField1.getText();
        String TrainingTime = jTextField2.getText();
        String Layers = jTextField3.getText();
        try {
            allData = weka.mlp(diretorio, learningRate, TrainingTime, Layers, folds);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RealizarTestes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RealizarTestes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RealizarTestes.class.getName()).log(Level.SEVERE, null, ex);
        }

    } else if (buttonSelected == 2) {
        String clusters = jTextField4.getText();
        try {
            allData = weka.rbf(diretorio, clusters, folds);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RealizarTestes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RealizarTestes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RealizarTestes.class.getName()).log(Level.SEVERE, null, ex);
        }

    } else if (buttonSelected == 3) {
        try {
            int porcentagem = Integer.parseInt(folds);
            allData = weka.regressaoLinear(diretorio,porcentagem);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RealizarTestes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RealizarTestes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    ResultadoTeste resultado = new ResultadoTeste();
    resultado.preencherResultado(allData);
    resultado.setVisible(true);


}//GEN-LAST:event_jPovoarActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Browse browse = new Browse();
    browse.setPovoarBanco(this);
    browse.setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    jLabel1.setVisible(true);
    jLabel2.setVisible(true);
    jLabel3.setVisible(true);
    jLabel4.setVisible(false);
    jLabel7.setText("Folds (CrossValidation):");
    jTextField1.setVisible(true);
    jTextField2.setVisible(true);
    jTextField3.setVisible(true);
    jTextField4.setVisible(false);
    buttonSelected = 1;
}//GEN-LAST:event_jRadioButton1ActionPerformed

private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    jLabel1.setVisible(false);
    jLabel2.setVisible(false);
    jLabel3.setVisible(false);
    jLabel4.setVisible(true);
    jLabel7.setText("Folds (CrossValidation):");
    jTextField1.setVisible(false);
    jTextField2.setVisible(false);
    jTextField3.setVisible(false);
    jTextField4.setVisible(true);
    buttonSelected = 2;
}//GEN-LAST:event_jRadioButton2ActionPerformed

private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

    jLabel1.setVisible(false);
    jLabel2.setVisible(false);
    jLabel3.setVisible(false);
    jLabel4.setVisible(false);
    jTextField1.setVisible(false);
    jTextField2.setVisible(false);
    jTextField3.setVisible(false);
    jTextField4.setVisible(false);
    jLabel7.setText("Porcentagem :");
    buttonSelected = 3;
}//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RealizarTestes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DadosAcesso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jDiretorio;
    private javax.swing.JTextField jFolds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jPovoar;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
